### ISSUE TITLE
Grouping only works with implied block form

### ISSUE THREAD

**Issue by Sharagoz** [ddengler/prawn-grouping#14]
Hello
The following works as expected:

```ruby
    Prawn::Document.new do
      group do
        40.times { text "1111" }
      end

      group do
        40.times { text "222" }
      end
    end

```

If I change to explicit block form, then the content is rendered twice and grouping doesnt happen:
```ruby
    Prawn::Document.new do |pdf|
      pdf.group do
        40.times { pdf.text "1111" }
      end

      pdf.group do
        40.times { pdf.text "222" }
      end
    end
```

Tested with Prawn 1.3.0 and the latest version of prawn-grouping from github/master

**Comment by ddengler** [comment]
Sorry for the late reply. This probably happens because you reference the original document within your group by using pdf.text in the curly braces. The following should also work:

```ruby
Prawn::Document.new do |pdf|
    pdf.group do |group_pdf|
        40.times { group_pdf.text "1111" }
    end

    pdf.group do  |group_pdf|
        40.times { group_pdf.text "222" }
    end
end
```
