### ISSUE TITLE
Unable to install using Prawn 2.2.2

### ISSUE THREAD

**Issue by clveranis** [ddengler/prawn-grouping#22]
Hi there, 

I see that your last commit was 20 days ago so I'm hoping this gem is still maintained as it seems like it will resolve an issue that I'm having with prawn. However, I'm using Prawn lock to version 2.2.2 and when I try to require this gem I get the following error: 

Resolving dependencies...
Bundler could not find compatible versions for gem "prawn":
  In snapshot (Gemfile.lock):
    prawn (= 2.2.2)

  In Gemfile:
    prawn (~> 2.2.2)

    prawn-grouping was resolved to 0.1.0, which depends on
      prawn (~> 0.15.0)

Any suggestions? Thanks!

**Comment by mlynarczyk** [comment]
@clveranis 

master branch works: `gem 'prawn-grouping', github: 'ddengler/prawn-grouping'`

**Comment by clveranis** [comment]
That worked, thank you!

**Comment by ddengler** [comment]
Thanks guys. I will look into updating / releasing a new version of the library for this.
